services:
  runodb:
    build: ./worker/.
    volumes:
      - ./volumes/runodb:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .dbEnv

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080



